apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  creationTimestamp: null
  name: cigna-test-pfdwp
  namespace: openshift-cluster-api-guests
spec:
  controlPlaneEndpoint:
    host: api.cigna-test.openshift.sboyle.internal
    port: 6443
  identityRef:
    kind: Secret
    name: vsphere-creds
  server: https://vcenter1.sboyle.internal
status: {}
